---
- name: Create config and other directories
  file:
    path: '{{ item }}'
    owner: '{{ cortex_service_user }}'
    group: 'adm'
    mode: '0750'
    state: directory
  with_items:
    - '{{ cortex_config_dir }}'
    - '{{ cortex_data_dir }}'
    - '{{ cortex_data_dir }}/rules'
    - '{{ cortex_rules_dir }}'
    - '{{ cortex_rules_dir }}/fake' # This is because we use auth_enabled:false

- name: Create Cortex configuration
  template:
    src: 'config.yml.j2'
    dest: '{{ cortex_config_file }}'
    owner: '{{ cortex_service_user }}'
    group: 'adm'
    mode: '0640'

- name: Create Cortex schema file
  template:
    src: 'schema.yml.j2'
    dest: '{{ cortex_schema_file }}'
    owner: '{{ cortex_service_user }}'
    group: 'adm'
    mode: '0640'

- name: Copy alerting rules files
  copy:
    src: '{{ item }}'
    dest: '{{ cortex_rules_dir }}/fake'
    owner: '{{ cortex_service_user }}'
    group: 'adm'
    mode: '0640'
  with_fileglob: "../files/rules/*.yml"
