---
- name: Create config and other directories
  file:
    path: '{{ item }}'
    owner: '{{ cortex_service_user }}'
    group: 'adm'
    mode: '0750'
    state: directory
  with_items:
    - '{{ cortex_config_dir }}'
    - '{{ cortex_data_dir }}'
    - '{{ cortex_wal_dir }}'

- name: Create Cortex configuration
  template:
    src: 'config.yml.j2'
    dest: '{{ cortex_config_file }}'
    owner: '{{ cortex_service_user }}'
    group: 'adm'
    mode: '0640'

- name: Create Cortex runtime config
  template:
    src: 'runtime.yml.j2'
    dest: '{{ cortex_runtime_file }}'
    owner: '{{ cortex_service_user }}'
    group: 'adm'
    mode: '0640'
