---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ cortex_service_name }}'
    consul_services:
      - name: '{{ cortex_service_name }}'
        tags: '{{ ["cortex", "metrics"] + cortex_target_modules }}'
        port: '{{ cortex_listen_port }}'
        address: '{{ ansible_local.tinc.vpn_ip }}'
        checks:
          - id: '{{ cortex_service_name }}-health'
            name: Cortex Healthcheck
            type: http
            http: 'http://localhost:{{ cortex_listen_port }}/'
