---
- name: Get Cassandra service addresses
  uri:
    url: '{{ consul_catalog_url }}/service/cassandra'
    method: GET
    validate_certs: no
  register: cassandra_services

- name: Get Query Frontend service addresses
  uri:
    url: '{{ consul_catalog_url }}/service/cortex-query-frontend'
    method: GET
    validate_certs: no
  register: query_frontend_services

- name: Extract service IP addresses
  set_fact:
    cassandra_nodes: |
      {{ cassandra_services.json
      | map(attribute="ServiceAddress")
      | reject("equalto", ansible_local.tinc.vpn_ip)
      | list }}
    cassandra_port: |
      {{ cassandra_services.json
      | map(attribute="ServicePort")
      | first }}

    cortex_query_frontend_addr: '{{ query_frontend_services.json[0]["ServiceAddress"] }}'
    cortex_query_frontend_port: '{{ query_frontend_services.json[0]["ServiceMeta"]["grpc_port"] }}'
