---
- name: Get Cassandra service addresses
  uri:
    url: '{{ consul_catalog_url }}/service/cassandra'
  register: cassandra_services

- name: Get Query Frontend service addresses
  uri:
    url: '{{ consul_catalog_url }}/service/cortex-query-frontend'
  register: query_frontend_services

- name: Get memcached service addresses
  uri:
    # WARNING: The tag is important to not match other clusters.
    url: '{{ consul_catalog_url }}/service/memcached?tag=cortex'
  register: memcached_services

- name: Extract service IP addresses
  set_fact:
    cortex_cassandra_nodes: |
      {{ cassandra_services.json
      | map(attribute="ServiceAddress")
      | reject("equalto", ansible_local.tinc.vpn_ip)
      | list }}
    cortex_cassandra_port: |
      {{ cassandra_services.json
      | map(attribute="ServicePort")
      | first | trim }}

    cortex_query_frontend_addr: '{{ query_frontend_services.json[0]["ServiceAddress"] }}'
    cortex_query_frontend_port: '{{ query_frontend_services.json[0]["ServiceMeta"]["grpc_port"] }}'

    cortex_memcached_addresses: |
      {{ memcached_services.json | json_query("[].[ServiceAddress, ServicePort]") | map('join', ':') | list }}
