---
- name: Get Memcached service addresses
  uri:
    # WARNING: The tag is important to not match other clusters.
    url: '{{ cortex_consul_catalog_url }}/service/memcached?tag=cortex'
  register: memcached_services

- name: Extract Memcached IP and port
  set_fact:
    cortex_memcached_addresses: |
      {{ memcached_services.json 
      | json_query("[].[ServiceAddress, ServicePort]")
      | map('join', ':') | list }}

- when: >
    "all" == cortex_target_modules or
    "querier" in cortex_target_modules
  block:
    - name: Get Query Frontend service addresses
      uri:
        url: '{{ cortex_consul_catalog_url }}/service/cortex?tag=query-frontend'
      register: qf_services

    - name: Extract Query Frontend IP and port
      set_fact:
        cortex_query_frontend_addr: '{{ qf_services.json[0]["ServiceAddress"] }}'
        cortex_query_frontend_port: '{{ qf_services.json[0]["ServiceMeta"]["grpc_port"] }}'
