---
- name: Create systemd Unit file
  template:
    src: 'cortex.service.j2'
    dest: '/lib/systemd/system/{{ cortex_service_name }}.service'
    mode: 0644
  register: cortex_service

- name: Reload Systemctl
  when: cortex_service.changed
  command: systemctl daemon-reload

- name: (Re)Start Service
  throttle: 1
  service:
    name: '{{ cortex_service_name }}.service'
    enabled: true
    state: |-
      {{ (
          cortex_binary.changed or
          cortex_config.changed or
          cortex_service.changed
         ) | ternary("restarted", "started") }}
